### ISSUE TITLE
Make gcspypi work on Python 3

### ISSUE THREAD

**Issue by ktong** [ethronsoft/gcspypi#3]
got error below when running on Python 3:
Traceback (most recent call last):
  File "/srv/venv/bin/gcspypi", line 11, in <module>
    load_entry_point('gcspypi==1.0.1', 'console_scripts', 'gcspypi')()
  File "/srv/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/srv/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/srv/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/srv/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/srv/venv/lib/python3.5/site-packages/ethronsoft/gcspypi/__main__.py", line 35
    """
      ^
SyntaxError: invalid syntax

**Comment by edoardofelici** [comment]
Hi ktong, I was making changes to make it work on python3 just to later find out that google gcloud related libraries (used for the authentication) only work on python2.7

https://cloud.google.com/sdk/downloads

"""
System requirements
Cloud SDK runs on Linux, Mac OS X and Windows, and requires Python 2.7.x.
"""
So for now, this will remain a python2.7 tool. 
I have updated the documentation accordingly, suggesting to use gcspypi in a virtualenv backed by python2.7.  Thanks for noticing though.
