### ISSUE TITLE
Error when running gcspypi --repository pypi   

### ISSUE THREAD

**Issue by NixBiks** [ethronsoft/gcspypi#9]
Very neat library! (if its working)

When running

    (venv) ➜  plx-annotator git:(master) ✗ gcspypi --repository pypi        

Then I get the following error

    Traceback (most recent call last):
      File "venv/bin/gcspypi", line 11, in <module>
        load_entry_point('gcspypi==1.0.7', 'console_scripts', 'gcspypi')()
      File "venv/lib/python3.6/site-packages/ethronsoft/gcspypi/__main__.py", line 42, in main
        handlers[args["command"]](config, args)
    KeyError: None

I have a bucket called `pypi`

**Comment by asaushkin** [comment]
@mr-bjerre Did you find the solution?

**Comment by NixBiks** [comment]
I’m not using the library

**Comment by aariyansh** [comment]
Even I am also getting the same error does anyone find this working . I even tried to define repository in ~/.gcspypirc and then upload the artifacts but it does not work . 
gcspypi --repository <repo_name> upload dist/my-package-1.0.2.tar.gz
using repository gcspypi-bucket
 connected                        
error: too many values to unpack (expected 2)

**Comment by ghost** [comment]
Same here, anyone working on the issue ?

**Comment by jerryvurbl** [comment]
This error looks to me like its caused when a `PKG-INFO` file inside the package has lines that do not have a ":" in them.  This apparently can happen with fields like "Description" or "License" which may have newlines.

One fix might be to only consider lines that match a regex like `^[^\s]+:\s+\S+` before `k, v = line.split(":")` below:

```
self = <ethronsoft.gcspypi.package.package_builder.PackageBuilder.__extract_source.<locals>.InfoCmd object at 0x10d6f4160>
target = <_io.TextIOWrapper name='./myapp-1.0.0/PKG-INFO' mode='r' encoding='UTF-8'>

    def __call__(self, target):
        m = {}
        for line in target.readlines():
>           k, v = line.split(":")
E           ValueError: too many values to unpack (expected 2)
```
